//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectotransmilenio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTAS_PARADEROS
    {
        public decimal ID_PARADERO { get; set; }
        public decimal ID_RUTA { get; set; }
        public decimal POSICION_RUTA { get; set; }
    }
}
