//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyectotransmilenio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INFRAESTRUCTURA_TRANSMILENIOEntities : DbContext
    {
        public INFRAESTRUCTURA_TRANSMILENIOEntities()
            : base("name=INFRAESTRUCTURA_TRANSMILENIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> BUSES { get; set; }
        public virtual DbSet<BUSES_VIAS> BUSES_VIAS { get; set; }
        public virtual DbSet<PARADERO> PARADEROS { get; set; }
        public virtual DbSet<RUTA> RUTAS { get; set; }
        public virtual DbSet<RUTAS_PARADEROS> RUTAS_PARADEROS { get; set; }
        public virtual DbSet<TIPOS_BUSES> TIPOS_BUSES { get; set; }
        public virtual DbSet<TIPOS_PARADEROS> TIPOS_PARADEROS { get; set; }
        public virtual DbSet<TIPOS_RUTAS> TIPOS_RUTAS { get; set; }
        public virtual DbSet<VIA> VIAS { get; set; }
        public virtual DbSet<VIAS_RUTAS> VIAS_RUTAS { get; set; }
    }
}
