//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTransmilenio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSMILENIO
    {
        public decimal ID { get; set; }
        public string NOMBRE_VIA { get; set; }
        public string TIPO_BUS { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string CONDUTOR { get; set; }
        public string COLOR { get; set; }
        public string TIPO_RUTA { get; set; }
        public string NOMBRE_RUTA { get; set; }
        public string TIPO_PARADERO { get; set; }
        public string NOMBRE_PARADERO { get; set; }
        public string UBICACION_PARADERO { get; set; }
        public decimal POSICION_VIA { get; set; }
        public decimal POSICION_RUTA { get; set; }
    }
}
