--Script Integridad Referencial de la BD INFRAESTRUCTURA_TRANSMILENIO
--Integrantes:
--				- Marilyn Astrid Chaparro Hurtado
--				- Juan Carlos Valderrama Camargo

------------------------------------------------------------------
--Creación de constrains de la BD
------------------------------------------------------------------
USE INFRAESTRUCTURA_TRANSMILENIO

ALTER TABLE ZONAS ADD
	CONSTRAINT PK_ID_ZON PRIMARY KEY (ID_ZONA),
	CONSTRAINT ZON_CK_IDZ CHECK (ID_ZONA > 0);

ALTER TABLE VIAS ADD
	CONSTRAINT PK_ID_VIA PRIMARY KEY (ID_VIA),
	CONSTRAINT VIA_CK_IDV CHECK (ID_VIA > 0),
	CONSTRAINT VIA_FK_IDZ FOREIGN KEY (ID_ZONA) REFERENCES ZONAS(ID_ZONA);

ALTER TABLE TIPOS_BUSES ADD
	CONSTRAINT PK_ID_TBUS PRIMARY KEY (ID_TIPO_BUS),
	CONSTRAINT TBUS_CK_IDTB CHECK (ID_TIPO_BUS > 0);

ALTER TABLE BUSES ADD
	CONSTRAINT PK_ID_BUS PRIMARY KEY (ID_BUS),
	CONSTRAINT BUS_CK_IDB CHECK (ID_BUS > 0),
	CONSTRAINT BUS_FK_IDTB FOREIGN KEY (ID_TIPO_BUS) REFERENCES TIPOS_BUSES(ID_TIPO_BUS);

ALTER TABLE BUSES_VIAS ADD
	CONSTRAINT PK_ID_BV PRIMARY KEY (ID_TIPO_BUS, ID_VIA);

ALTER TABLE TIPOS_RUTAS ADD
	CONSTRAINT PK_ID_TRUT PRIMARY KEY (ID_TIPO_RUTA),
	CONSTRAINT TRUT_CK_IDTR CHECK (ID_TIPO_RUTA > 0);

ALTER TABLE RUTAS ADD
	CONSTRAINT PK_ID_RUT PRIMARY KEY (ID_RUTA),
	CONSTRAINT RUT_CK_IDR CHECK (ID_RUTA > 0),
	CONSTRAINT RUT_FK_IDB FOREIGN KEY (ID_BUS) REFERENCES BUSES(ID_BUS),
	CONSTRAINT RUT_FK_IDTR FOREIGN KEY (ID_TIPO_RUTA) REFERENCES TIPOS_RUTAS(ID_TIPO_RUTA);

ALTER TABLE VIAS_RUTAS ADD
	CONSTRAINT PK_ID_VR PRIMARY KEY (ID_VIA, ID_RUTA);

ALTER TABLE TIPOS_PARADEROS ADD
	CONSTRAINT PK_ID_TPAR PRIMARY KEY (ID_TIPO_PAR),
	CONSTRAINT TPAR_CK_IDTP CHECK (ID_TIPO_PAR > 0);

ALTER TABLE PARADEROS ADD
	CONSTRAINT PK_ID_PAR PRIMARY KEY (ID_PARADERO),
	CONSTRAINT PAR_CK_IDP CHECK (ID_PARADERO > 0),
	CONSTRAINT PAR_FK_IDTP FOREIGN KEY (ID_TIPO_PAR) REFERENCES TIPOS_PARADEROS(ID_TIPO_PAR),
	CONSTRAINT PAR_FK_IDV FOREIGN KEY (ID_VIA) REFERENCES VIAS(ID_VIA);

ALTER TABLE RUTAS_PARADEROS ADD
	CONSTRAINT PK_ID_RP PRIMARY KEY (ID_PARADERO, ID_RUTA);

